### ISSUE TITLE
Volume is not handled correctly in SB Live/SB Audigy

### ISSUE THREAD

**Issue by vicokoby** [Baron-von-Riedesel/VSBHDA#12]
Volume is not managed correctly on my SB0100, using up to /VOL8 the sound is very low. On the other hand, with /VOL9 the sound is very loud and distorted.
I think this only happens with SB Live and SB Audigy soundcards.

**Comment by Baron-von-Riedesel** [comment]
Ok, will check that. May take a while due to "health issues".

**Comment by Baron-von-Riedesel** [comment]
I can confirm this issue. Fix is simple and on the way...

**Comment by Baron-von-Riedesel** [comment]
fixes. Use https://github.com/Baron-von-Riedesel/VSBHDA/releases/tag/v1.5pre1 to try.

**Comment by vicokoby** [comment]
I still notice the volume a little low up to /vol8, but I think this happens with any sound card.
However, now with /vol9 the sound is no longer distorted and the volume is quite accurate.
Thank you!
