### ISSUE TITLE
detect whether VSBHDA is present?

### ISSUE THREAD

**Issue by sezero** [Baron-von-Riedesel/VSBHDA#6]
SBEMU presence can be detected by searching int2d amis appstring. Is it possible to detect VSBHDA presence in any way?

**Comment by Baron-von-Riedesel** [comment]
Well, the way vsbhda checks if it is already installed is to detect if a soundblaster is installed - by accessing the SB ports.

**Comment by sezero** [comment]
OK then. Thanks.
